include: package:flutter_lints/flutter.yaml

analyzer: 
  language: 
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  errors:
    missing_required_param: warning
    missing_return: warning

linter:
  rules:
    use_key_in_widget_constructors: false
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_classes_with_only_static_members: true
    avoid_field_initializers_in_const_classes: true
    avoid_slow_async_io: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    flutter_style_todos: true
    no_adjacent_strings_in_list: true
    package_api_docs: true
    prefer_asserts_in_initializer_lists: true
    prefer_final_in_for_each: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_null_aware_assignments: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    prefer_foreach: true
    prefer_final_locals: true
    directives_ordering: true
