name: beauty_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.0.1
  flutter_hooks: ^0.21.2
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  flutter_easyloading: ^3.0.5
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  animated_bottom_navigation_bar: ^1.4.0
  intl: ^0.19.0
  collection: ^1.19.0
  get_it: ^8.0.3
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/

  fonts:
    - family: NotoSansTC
      fonts:
        - asset: assets/fonts/NotoSansTC-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansTC-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansTC-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansTC-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansTC-Regular.ttf
          weight: 400