# .github/ISSUE_TEMPLATE/bug_report.yml

name: "🐛 App Bug Report"
description: "Report a bug encountered in the app."
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Detailed steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Tap on '....'
        3. Observe the issue.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "Please attach screenshots that clearly show the bug. You can drag and drop images directly into this box."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "### Device Information"

  - type: input
    id: device-model
    attributes:
      label: "Device"
      placeholder: "e.g., iPhone 13, Samsung Galaxy S21, Pixel 6"
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: "OS Version"
      placeholder: "e.g., iOS 15.5, Android 12"
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: "App Version"
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or information about the bug that might be helpful."
    validations:
      required: false